import type { Model } from "#ai/model/index";
import type { Api } from "#ai/protocol/ids";

function propertyKey(key: string): string {
	return /^[A-Za-z_$][\w$]*$/.test(key) ? key : JSON.stringify(key);
}

function valueLiteral(value: unknown): string {
	if (Array.isArray(value)) return `[${value.map(valueLiteral).join(", ")}]`;
	if (value && typeof value === "object") {
		return `{ ${Object.entries(value)
			.map(([key, entryValue]) => `${propertyKey(key)}: ${valueLiteral(entryValue)}`)
			.join(", ")} }`;
	}
	return JSON.stringify(value);
}

export function serialize(grouped: Record<string, Record<string, Model<Api>>>): string {
	let output = `// This file is auto-generated by src/model/generate.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "#ai/model/index";

export const MODELS = {
`;

	for (const provider of Object.keys(grouped).sort()) {
		output += `\t${propertyKey(provider)}: {\n`;
		for (const id of Object.keys(grouped[provider]).sort()) {
			const model = grouped[provider][id];
			output += `\t\t${propertyKey(model.id)}: {\n`;
			output += `\t\t\tid: ${JSON.stringify(model.id)},\n`;
			output += `\t\t\tname: ${JSON.stringify(model.name)},\n`;
			output += `\t\t\tapi: ${JSON.stringify(model.api)},\n`;
			output += `\t\t\tprovider: ${JSON.stringify(model.provider)},\n`;
			output += `\t\t\tbaseUrl: ${JSON.stringify(model.baseUrl)},\n`;
			if (model.compat) {
				output += `\t\t\tcompat: {\n`;
				for (const [key, value] of Object.entries(model.compat)) {
					output += `\t\t\t\t${propertyKey(key)}: ${valueLiteral(value)},\n`;
				}
				output += `\t\t\t},\n`;
			}
			output += `\t\t\treasoning: ${model.reasoning},\n`;
			if (model.thinkingLevelMap) output += `\t\t\tthinkingLevelMap: ${valueLiteral(model.thinkingLevelMap)},\n`;
			output += `\t\t\tinput: ${valueLiteral(model.input)},\n`;
			output += `\t\t\tcost: {\n`;
			output += `\t\t\t\tinput: ${model.cost.input},\n`;
			output += `\t\t\t\toutput: ${model.cost.output},\n`;
			output += `\t\t\t\tcacheRead: ${model.cost.cacheRead},\n`;
			output += `\t\t\t\tcacheWrite: ${model.cost.cacheWrite},\n`;
			output += `\t\t\t},\n`;
			output += `\t\t\tcontextWindow: ${model.contextWindow},\n`;
			output += `\t\t\tmaxTokens: ${model.maxTokens},\n`;
			output += `\t\t} satisfies Model<${JSON.stringify(model.api)}>,\n`;
		}
		output += `\t},\n`;
	}

	return `${output}} as const;\n`;
}
