import type { WorkflowSkillHelp } from "#workflows/skills/workflow-help-types";

export const ULTRAGOAL_SKILL_HELP: WorkflowSkillHelp = {
	skill: "ultragoal",
	label: "Ultragoal",
	docs: [
		"packages/workflows/src/skills/ultragoal/SKILL.md",
		"packages/workflows/src/skills/ultragoal/references/commands.md",
		"packages/workflows/src/skills/ultragoal/assets/schema.json",
	],
	commandOrder: [
		"`pi workflow state ultragoal read --session <session-id> --json` to inspect state.",
		'`pi workflow ultragoal status --input \'{"sessionId":"<session-id>"}\' --json` to inspect goals.',
		'`pi workflow ultragoal create-plan --input \'{"sessionId":"<session-id>","brief":"approved goal..."}\' --json` when no goal plan exists.',
		'`pi workflow ultragoal start-next --input \'{"sessionId":"<session-id>"}\' --json` before implementation.',
		'`pi workflow ultragoal checkpoint --input \'{"sessionId":"<session-id>","goalId":"goal-1","status":"active","evidence":"..."}\' --json` after progress or completion evidence; each checkpoint writes a state-only restore snapshot.',
		'`pi workflow ultragoal restore-checkpoint --input \'{"sessionId":"<session-id>"}\' --json` only after later-task failure when you need to restore Ultragoal state to the latest valid checkpoint. Pass `expectedPlanHash` from `status.planHash` when available.',
		'`pi workflow ultragoal record-obstacle --input \'{"sessionId":"<session-id>","goalId":"goal-1","kind":"evidence_missing","title":"...","objective":"...","evidence":"...","rationale":"..."}\' --json` when review creates a typed durable obstacle.',
		'`pi workflow ultragoal classify-blocker --input \'{"sessionId":"<session-id>","classification":"human_blocked","evidence":"..."}\' --json` only for policy-classified failed/blocked work.',
		'`pi workflow ultragoal guard --input \'{"sessionId":"<session-id>"}\' --json` when readiness or quality is uncertain.',
	],
	referenceFooter: [
		"Always pass the current session id as `sessionId` in action payloads. Complete checkpoints require the nested `qualityGate` shape from `../assets/schema.json`. Restore is state-only: it restores `.pi/<session-id>/ultragoal/goals.json` and workflow state, but it never rolls back workspace files.",
	],
	agentFlow: [
		"Use only for approved concrete execution; route vague requests to deep-interview or ralplan.",
		"Create/resume the plan, `start-next` before implementation, then edit and verify.",
		"Use `checkpoint` with substantive evidence; complete checkpoints need the full nested qualityGate and create state-only restore points.",
		"Use record-obstacle/classify-blocker only for durable blockers; do not widen scope.",
	],
	actions: {
		"create-plan": {
			summary: "Create an ultragoal execution plan.",
			when: "Use when approved execution has no current goal ledger.",
			input: [
				"sessionId: string (required; current session)",
				"brief: string (required)",
				"goalMode?: aggregate|per-story",
			],
			example: `pi workflow ultragoal create-plan --input '{"sessionId":"<session-id>","brief":"approved goal..."}' --json`,
		},
		status: {
			summary: "Read full ultragoal status.",
			when: "Use before selecting the next action.",
			input: ["sessionId: string (required; current session)"],
			example: `pi workflow ultragoal status --input '{"sessionId":"<session-id>"}' --json`,
		},
		"start-next": {
			summary: "Start the next pending goal.",
			when: "Use before implementation work on a goal.",
			input: ["sessionId: string (required; current session)", "retryFailed?: boolean"],
			example: `pi workflow ultragoal start-next --input '{"sessionId":"<session-id>"}' --json`,
		},
		checkpoint: {
			summary: "Record progress, completion, failure, or blocked evidence for a goal.",
			when: "Use after meaningful progress or verification; complete status requires full qualityGate.",
			input: [
				"sessionId: string (required; current session)",
				"goalId: string (required)",
				"status: pending|active|complete|failed|blocked|review_blocked|superseded (required)",
				"evidence?: string",
				"qualityGate?: object (required for complete)",
			],
			example: `pi workflow ultragoal checkpoint --input '{"sessionId":"<session-id>","goalId":"goal-1","status":"active","evidence":"..."}' --json`,
		},
		"restore-checkpoint": {
			summary: "Restore Ultragoal state to the latest valid checkpoint.",
			when: "Use after a later task failed and you need to retry from the last successful task state. This does not roll back workspace files.",
			input: ["sessionId: string (required; current session)", "checkpointId?: string", "expectedPlanHash?: string"],
			example: `pi workflow ultragoal restore-checkpoint --input '{"sessionId":"<session-id>"}' --json`,
		},
		"record-obstacle": {
			summary: "Record a typed obstacle and its blocker-resolution goal.",
			when: "Use when review or verification finds a durable resolvable obstacle.",
			input: [
				"sessionId: string (required; current session)",
				"goalId: string (required)",
				"kind: review_failure|evidence_missing|scope_drift|contract_contradiction (required)",
				"title: string (required)",
				"objective: string (required)",
				"evidence: string (required)",
				"rationale: string (required)",
				"criterion?: string (required for review_failure and scope_drift)",
				"regression?: object (required by regression-sensitive kinds)",
			],
			example: `pi workflow ultragoal record-obstacle --input '{"sessionId":"<session-id>","goalId":"goal-1","kind":"evidence_missing","title":"...","objective":"...","evidence":"...","rationale":"..."}' --json`,
		},
		"classify-blocker": {
			summary: "Classify a blocker before a failed/blocked checkpoint can close work.",
			when: "Use only when the blocker is truly human-blocked or otherwise classified by policy.",
			input: [
				"sessionId: string (required; current session)",
				"classification: human_blocked|resolvable (required)",
				"evidence: string (required)",
				"goalId?: string",
			],
			example: `pi workflow ultragoal classify-blocker --input '{"sessionId":"<session-id>","classification":"human_blocked","evidence":"..."}' --json`,
		},
		guard: {
			summary: "Run the ultragoal quality guard.",
			when: "Use before or after checkpoints when quality/readiness is uncertain.",
			input: ["sessionId: string (required; current session)", "goalId?: string", "currentObjective?: string"],
			example: `pi workflow ultragoal guard --input '{"sessionId":"<session-id>","goalId":"goal-1"}' --json`,
		},
	},
	typedArgs: [
		{ name: "brief", type: "string" },
		{ name: "goalMode", type: "enum", enumValues: ["aggregate", "per-story"] },
		{ name: "goalId", type: "string" },
		{ name: "checkpointId", type: "string" },
		{ name: "expectedPlanHash", type: "string" },
		{ name: "status", type: "string" },
		{ name: "receiptKind", type: "enum", enumValues: ["per-goal", "final-aggregate"] },
	],
} as const;
