import type { WorkflowSkillHelp } from "#workflows/skills/workflow-help-types";

export const DEEP_INTERVIEW_SKILL_HELP: WorkflowSkillHelp = {
	skill: "deep-interview",
	label: "Deep Interview",
	docs: [
		"packages/workflows/src/skills/deep-interview/SKILL.md",
		"packages/workflows/src/skills/deep-interview/references/commands.md",
		"packages/workflows/src/skills/deep-interview/assets/schema.json",
	],
	commandOrder: [
		"`pi workflow state deep-interview read --session <id> --json` to inspect state.",
		"`pi workflow deep-interview plan-question` before asking each single user-facing question.",
		"`pi workflow deep-interview record-answer` after the user answers.",
		"`pi workflow deep-interview record-scoring` after recording the answer.",
		"`pi workflow deep-interview read-compact` when resuming or budgeting prompt context.",
		"`pi workflow deep-interview closure-check` before final spec writing.",
		"`pi workflow deep-interview restate-goal` after closure passes.",
		"`pi workflow deep-interview write-spec` after the closure and restatement gates pass.",
	],
	referenceFooter: [
		"Always pass the current session id as `sessionId` in action payloads. Do not directly edit `.pi/**` workflow state.",
	],
	agentFlow: [
		"Initialize/read state with `pi workflow state deep-interview ...` before asking questions.",
		"Call `plan-question` before each user-facing question, then ask exactly one question.",
		"After the answer, call `record-answer`, then `record-scoring` with scores, ambiguity, and triggers.",
		"Before final spec: run `closure-check`, then `restate-goal`, then `write-spec`.",
	],
	actions: {
		"plan-question": {
			summary: "Plan the next targeted question and mark the round waiting for an answer.",
			when: "Use immediately before asking each Deep Interview question.",
			input: [
				"sessionId?: string (current session; required in agent/runtime use)",
				"round: number (required)",
				"questionText: string (required; exact one-question prompt)",
				"questionId?: string",
				"component?: string",
				"dimension?: string",
				"ambiguity?: number",
				"rationale?: string",
			],
			example: `pi workflow deep-interview plan-question --input '{"sessionId":"h-...","round":1,"questionText":"..."}' --json`,
		},
		"record-answer": {
			summary: "Record or replace an answered round, including optional topology lock.",
			when: "Use after the user answers and before scoring.",
			input: [
				"sessionId?: string",
				"round?: number",
				"round_id?: string",
				"questionId?: string",
				"questionText?: string",
				"component?: string",
				"dimension?: string",
				"ambiguity?: number",
				"selectedOptions?: string[]",
				"customInput?: string",
				"topology?: object (Round 0 topology lock)",
			],
			example: `pi workflow deep-interview record-answer --input '{"sessionId":"h-...","round":1,"customInput":"..."}' --json`,
		},
		"record-scoring": {
			summary: "Persist scores, ambiguity, triggers, and advisory metadata for a round.",
			when: "Use after `record-answer`; this moves the round to scored state.",
			input: [
				"sessionId?: string",
				"round: number (required)",
				"scores: object (required; dimension scores)",
				"ambiguity: number (required)",
				"round_id?: string",
				"questionId?: string",
				"triggers?: object[]",
				"metadata?: object",
			],
			example: `pi workflow deep-interview record-scoring --input '{"sessionId":"h-...","round":1,"scores":{"goal":0.6,"constraints":0.4,"criteria":0.3},"ambiguity":0.57}' --json`,
		},
		"read-compact": {
			summary: "Read prompt-efficient interview state.",
			when: "Use when resuming or before composing a prompt from large history.",
			input: ["sessionId?: string", "lastN?: number"],
			example: `pi workflow deep-interview read-compact --input '{"sessionId":"h-...","lastN":3}' --json`,
		},
		"closure-check": {
			summary: "Run the closure/acceptance guard before spec writing.",
			when: "Use only when ambiguity is at/below threshold or the user explicitly exits early.",
			input: ["sessionId?: string"],
			example: `pi workflow deep-interview closure-check --input '{"sessionId":"h-..."}' --json`,
		},
		"restate-goal": {
			summary: "Record the one-sentence goal confirmation gate.",
			when: "Use after closure passes and before `write-spec`.",
			input: [
				"sessionId?: string",
				"restatedGoal: string (required)",
				"confirm: Yes|Adjust|Missing (required)",
				"adjustment?: string",
			],
			example: `pi workflow deep-interview restate-goal --input '{"sessionId":"h-...","restatedGoal":"...","confirm":"Yes"}' --json`,
		},
		"write-spec": {
			summary: "Persist the finalized spec and optionally hand off to another workflow.",
			when: "Use only after `closure-check` and `restate-goal` gates pass, unless explicitly allowing early exit.",
			input: [
				"sessionId?: string",
				"spec: string (required; markdown content or readable file path)",
				"slug?: string",
				"handoff?: ralplan|team|ultragoal|stop",
				"allowEarlyExit?: boolean",
			],
			example: `pi workflow deep-interview write-spec --input '{"sessionId":"h-...","slug":"my-spec","spec":"# Spec...","handoff":"ralplan"}' --json`,
		},
	},
	typedArgs: [
		{ name: "quick", type: "boolean" },
		{ name: "standard", type: "boolean" },
		{ name: "deep", type: "boolean" },
		{ name: "threshold", type: "number" },
		{ name: "handoff", type: "enum", enumValues: ["ralplan", "team", "ultragoal", "stop"] },
	],
} as const;
