import type { WorkflowSkillHelp } from "#workflows/skills/workflow-help-types";

export const DEEP_INTERVIEW_SKILL_HELP: WorkflowSkillHelp = {
	skill: "deep-interview",
	label: "Deep Interview",
	docs: [
		"packages/workflows/src/skills/deep-interview/SKILL.md",
		"packages/workflows/src/skills/deep-interview/references/commands.md",
		"packages/workflows/src/skills/deep-interview/assets/schema.json",
	],
	commandOrder: [
		"`pi workflow state deep-interview read --session <session-id> --json` to inspect state.",
		'`pi workflow deep-interview plan-question --input \'{"sessionId":"<session-id>","round":1,"questionId":"q1","questionText":"...","rationale":"..."}\' --json` before asking each single user-facing question.',
		'`pi workflow deep-interview record-answer --input \'{"sessionId":"<session-id>","round":1,"questionId":"q1","questionText":"...","customInput":"..."}\' --json` after the user answers.',
		'`pi workflow deep-interview record-scoring --input \'{"sessionId":"<session-id>","round":1,"questionId":"q1","scores":{"goal":0.6},"ambiguity":0.3}\' --json` after recording the answer.',
		'`pi workflow deep-interview closure-check --input \'{"sessionId":"<session-id>"}\' --json` before final spec writing.',
		'`pi workflow deep-interview restate-goal --input \'{"sessionId":"<session-id>","restatedGoal":"...","confirm":"Yes"}\' --json` after closure passes.',
		'`pi workflow deep-interview write-spec --input \'{"sessionId":"<session-id>","slug":"my-spec","spec":"# Spec...","handoff":"stop"}\' --json` after the closure and restatement gates pass. A `ralplan` handoff also requires an explicit `runId`.',
	],
	referenceFooter: [
		"Always pass the current session id as `sessionId` in action payloads. Do not directly edit `.pi/**` workflow state.",
	],
	agentFlow: [
		"Initialize/read state with `pi workflow state deep-interview ...` before asking questions.",
		"Call `plan-question` before each user-facing question, then ask exactly one question.",
		"After the answer, call `record-answer`, then `record-scoring` with scores, ambiguity, and triggers.",
		"Before final spec: run `closure-check`, then `restate-goal`, then `write-spec`.",
	],
	actions: {
		"plan-question": {
			summary: "Plan the next targeted question and mark the round waiting for an answer.",
			when: "Use immediately before asking each Deep Interview question.",
			input: [
				"sessionId: string (required; current session)",
				"round: number (required)",
				"questionId: string (required; stable question identity)",
				"questionText: string (required; exact one-question prompt)",
				"component?: string",
				"dimension?: string",
				"ambiguity?: number",
				"rationale: string (required; bottleneck reason)",
			],
			example: `pi workflow deep-interview plan-question --input '{"sessionId":"<session-id>","round":1,"questionId":"q1","questionText":"...","rationale":"..."}' --json`,
		},
		"record-answer": {
			summary: "Record or replace an answered round, including optional topology lock.",
			when: "Use after the user answers and before scoring.",
			input: [
				"sessionId: string (required; current session)",
				"round: number (required)",
				"questionId: string (required; must match the planned question)",
				"questionText: string (required; must match the planned question)",
				"round_id?: string",
				"component?: string",
				"dimension?: string",
				"ambiguity?: number",
				"selectedOptions?: string[]",
				"customInput?: string",
				"topology?: object (Round 0 topology lock)",
			],
			example: `pi workflow deep-interview record-answer --input '{"sessionId":"<session-id>","round":1,"questionId":"q1","questionText":"...","customInput":"..."}' --json`,
		},
		"record-scoring": {
			summary: "Persist scores, ambiguity, triggers, and advisory metadata for a round.",
			when: "Use after `record-answer`; this moves the round to scored state.",
			input: [
				"sessionId: string (required; current session)",
				"round: number (required)",
				"questionId: string (required; must match the answered question)",
				"scores: object (required; dimension scores)",
				"ambiguity: number (required)",
				"round_id?: string",
				"triggers?: object[]",
				"metadata?: object",
			],
			example: `pi workflow deep-interview record-scoring --input '{"sessionId":"<session-id>","round":1,"questionId":"q1","scores":{"goal":0.6,"constraints":0.4,"criteria":0.3},"ambiguity":0.57}' --json`,
		},
		"closure-check": {
			summary: "Run the closure/acceptance guard before spec writing.",
			when: "Use only when ambiguity is at or below the threshold.",
			input: ["sessionId: string (required; current session)"],
			example: `pi workflow deep-interview closure-check --input '{"sessionId":"<session-id>"}' --json`,
		},
		"restate-goal": {
			summary: "Record the one-sentence goal confirmation gate.",
			when: "Use after closure passes and before `write-spec`.",
			input: [
				"sessionId: string (required; current session)",
				"restatedGoal: string (required)",
				"confirm: Yes|Adjust|Missing (required)",
				"adjustment?: string",
			],
			example: `pi workflow deep-interview restate-goal --input '{"sessionId":"<session-id>","restatedGoal":"...","confirm":"Yes"}' --json`,
		},
		"write-spec": {
			summary: "Persist the finalized spec and apply the explicit handoff decision.",
			when: "Use only after `closure-check` and `restate-goal` gates pass.",
			input: [
				"sessionId: string (required; current session)",
				"slug: string (required)",
				"spec: string (required; markdown content or readable file path)",
				"handoff: ralplan|team|ultragoal|stop (required)",
				"runId?: string (required for ralplan handoff)",
			],
			example: `pi workflow deep-interview write-spec --input '{"sessionId":"<session-id>","slug":"my-spec","spec":"# Spec...","handoff":"ralplan","runId":"ralplan-my-spec"}' --json`,
		},
	},
	typedArgs: [
		{ name: "quick", type: "boolean" },
		{ name: "standard", type: "boolean" },
		{ name: "deep", type: "boolean" },
		{ name: "threshold", type: "number" },
		{ name: "handoff", type: "enum", enumValues: ["ralplan", "team", "ultragoal", "stop"] },
	],
} as const;
