/**
 * Public extension API contracts.
 */

export type {
	AgentToolResult,
	AgentToolUpdateCallback,
	StructuredReceipt,
	ToolExecutionMode,
} from "@tsuuanmi/pi-agent";
export type { ExecOptions, ExecResult } from "#pi/exec/exec";
export type {
	CompactOptions,
	ContextUsage,
	ExtensionCommandContext,
	ExtensionContext,
	ExtensionMode,
	ReplacedSessionContext,
} from "#pi/runtime/context-types";
export type {
	AppendEntryHandler,
	Extension,
	ExtensionActions,
	ExtensionAPI,
	ExtensionCommandContextActions,
	ExtensionContextActions,
	ExtensionError,
	ExtensionFactory,
	ExtensionFlag,
	ExtensionRuntime,
	ExtensionShortcut,
	GetActiveToolsHandler,
	GetAllToolsHandler,
	GetCommandsHandler,
	GetThinkingLevelHandler,
	LoadExtensionsResult,
	MessageRenderer,
	MessageRenderOptions,
	RegisteredCommand,
	RegisteredTool,
	ResolvedCommand,
	SendMessageHandler,
	SendUserMessageHandler,
	SetActiveToolsHandler,
	SetLabelHandler,
	SetModelHandler,
	SetThinkingLevelHandler,
	ToolInfo,
} from "#pi/runtime/extension-types";
export type { ProviderConfig, ProviderModelConfig } from "#pi/api/provider-types";
export type {
	ToolDefinition,
	ToolRenderContext,
	ToolRenderResultOptions,
} from "#pi/api/tool-types";
export type {
	AutocompleteProviderFactory,
	EditorFactory,
	ExtensionUIContext,
	ExtensionUIDialogOptions,
	ExtensionWidgetOptions,
	TerminalInputHandler,
	WidgetPlacement,
	WorkingIndicatorOptions,
} from "#pi/api/ui-types";
export type {
	AfterProviderResponseEvent,
	AgentEndEvent,
	AgentStartEvent,
	BashToolCallEvent,
	BashToolResultEvent,
	BeforeAgentStartEvent,
	BeforeAgentStartEventResult,
	BeforeProviderRequestEvent,
	BeforeProviderRequestEventResult,
	ContextEvent,
	ContextEventResult,
	CustomToolCallEvent,
	CustomToolResultEvent,
	EditToolCallEvent,
	EditToolResultEvent,
	ExtensionEvent,
	FindToolCallEvent,
	FindToolResultEvent,
	GrepToolCallEvent,
	GrepToolResultEvent,
	InputEvent,
	InputEventResult,
	InputSource,
	LsToolCallEvent,
	LsToolResultEvent,
	MessageEndEvent,
	MessageStartEvent,
	MessageUpdateEvent,
	ModelSelectEvent,
	ModelSelectSource,
	ReadToolCallEvent,
	ReadToolResultEvent,
	ResourcesDiscoverEvent,
	ResourcesDiscoverResult,
	SessionBeforeCompactEvent,
	SessionBeforeCompactResult,
	SessionBeforeForkEvent,
	SessionBeforeForkResult,
	SessionBeforeSwitchEvent,
	SessionBeforeSwitchResult,
	SessionBeforeTreeEvent,
	SessionBeforeTreeResult,
	SessionCompactEvent,
	SessionEvent,
	SessionShutdownEvent,
	SessionStartEvent,
	SessionTreeEvent,
	ToolCallEvent,
	ToolCallEventResult,
	ToolExecutionEndEvent,
	ToolExecutionStartEvent,
	ToolExecutionUpdateEvent,
	ToolResultEvent,
	ToolResultEventResult,
	TreePreparation,
	TurnEndEvent,
	TurnStartEvent,
	UserBashEvent,
	UserBashEventResult,
	WriteToolCallEvent,
	WriteToolResultEvent,
} from "#pi/extensions/hooks/event-types";
export type { ExtensionHandler, ExtensionHookAPI } from "#pi/extensions/hooks/extension-api-hooks";
export {
	isBashToolResult,
	isEditToolResult,
	isFindToolResult,
	isGrepToolResult,
	isLsToolResult,
	isReadToolResult,
	isToolCallEventType,
	isWriteToolResult,
} from "#pi/extensions/hooks/event-types";
export { defineTool } from "#pi/api/tool-types";
export type { AppKeybinding, KeybindingsManager } from "#pi/settings/keybindings";
export type { BuildSystemPromptOptions } from "#pi/skills/system-prompt";
